name: CustomizableFishing
version: 0.50
main: me.dami.net.CustomFishing.Main.CustomizableFishing
api-version: 1.19
depend: [ WorldGuard, WorldEdit ]
authors: [ gewoondami60 ]
description: custom region fishing
commands:
  fishing:
    description: fish away
